import sys,time,json,urllib.request,subprocess,os,atexit,signal
from pathlib import Path
os.chdir(Path(__file__).resolve().parent.parent)
from playwright.sync_api import sync_playwright
out=Path(os.environ.get('STUDIO_RESULTS_DIR','benchmark-results/studio'));out.mkdir(parents=True,exist_ok=True)
server=subprocess.Popen(['npm','start','--','--host','127.0.0.1','--port','4930','--live-reload=false','--hmr=false'],cwd='.',stdout=open(out/'server.log','w'),stderr=subprocess.STDOUT,start_new_session=True)
atexit.register(lambda:os.killpg(server.pid,signal.SIGTERM))
for _ in range(60):
 try:urllib.request.urlopen('http://127.0.0.1:4930').close();break
 except:time.sleep(1)
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_EXECUTABLE'),headless=True,args=['--no-sandbox','--disable-dev-shm-usage'])
 page=browser.new_page(viewport={'width':1600,'height':1100},accept_downloads=True)
 page.on('pageerror',lambda e:print('ERROR',str(e),flush=True))
 page.goto('http://127.0.0.1:4930/studio');print('inputs',page.locator('input[type=file]').evaluate_all('(els)=>els.map(e=>({accept:e.accept,html:e.outerHTML}))'),flush=True)
 page.wait_for_function("window.ng && ng.getComponent(document.querySelector('app-studio-canvas'))?.facade")
 page.locator('input[type=file][accept*="pdf"]').first.set_input_files(str(Path('regression-fixtures/studio/studio-regression.pdf').resolve()))
 page.wait_for_function("window.ng && document.querySelector('app-studio-canvas') && ng.getComponent(document.querySelector('app-studio-canvas'))?.facade.hasDocument()")
 page.wait_for_timeout(1500)
 data=page.evaluate("async()=>{let c=ng.getComponent(document.querySelector('app-studio-canvas'));await c.facade.ensureCurrentPageContent();return c.objectService.listForPage(1)}")
 (out/'fixed-objects.json').write_text(json.dumps(data,indent=2))
 text=next(x for x in data if x.get('text')=='Edit this original sentence')
 assert text['pdfText']['baselineYPdf']==680
 assert text['bounds']['y']<.2
 page.get_by_role('button',name='Edit PDF Text',exact=True).click()
 page.locator('[data-object-id="'+text['id']+'"]').click()
 editor=page.get_by_role('textbox',name='Edit PDF text',exact=True)
 editor.fill('Edit this longer replacement sentence')
 page.get_by_role('button',name='Finish text edit',exact=True).click()
 page.wait_for_function("ng.getComponent(document.querySelector('app-studio-canvas')).committedPreview()")
 page.screenshot(path=str(out/'text-preview.png'),full_page=True)
 with page.expect_download() as d:page.get_by_role('button',name='Export PDF',exact=True).click()
 d.value.save_as(out/'text-edited.pdf')
 page.get_by_role('button',name='Edit PDF Image',exact=True).click()
 image=next(x for x in data if x['type']=='image')
 with page.expect_file_chooser() as chooser:page.locator('[data-object-id="'+image['id']+'"]').click()
 chooser.value.set_files(str(Path('regression-fixtures/studio/replacement.png').resolve()))
 page.wait_for_function("()=>ng.getComponent(document.querySelector('app-studio-canvas')).objectService.listForPage(1).some(x=>x.pdfImage?.replaced)")
 with page.expect_download() as d:page.get_by_role('button',name='Export PDF',exact=True).click()
 d.value.save_as(out/'text-image-edited.pdf')
 page.wait_for_timeout(1500)
 page.wait_for_function("ng.getComponent(document.querySelector('app-studio-canvas')).committedPreview()")
 page.screenshot(path=str(out/'image-preview.png'),full_page=True)
 # Undo/redo retains the image and text edits independently.
 page.evaluate("ng.getComponent(document.querySelector('app-studio-canvas')).facade.undo()")
 assert not page.evaluate("ng.getComponent(document.querySelector('app-studio-canvas')).objectService.listForPage(1).some(x=>x.pdfImage?.replaced)")
 page.evaluate("ng.getComponent(document.querySelector('app-studio-canvas')).facade.redo()")
 assert page.evaluate("ng.getComponent(document.querySelector('app-studio-canvas')).objectService.listForPage(1).some(x=>x.pdfImage?.replaced)")
 # Export must flush the active textarea, including Unicode fallback glyphs.
 page.get_by_role('button',name='Edit PDF Text',exact=True).click()
 page.locator('[data-object-id="'+text['id']+'"]').click()
 page.get_by_role('textbox',name='Edit PDF text',exact=True).fill('Edited draft Ω Ж')
 with page.expect_download() as d:page.get_by_role('button',name='Export PDF',exact=True).click()
 d.value.save_as(out/'draft-unicode.pdf')
 page.wait_for_timeout(1000)
 assert page.evaluate("ng.getComponent(document.querySelector('app-studio-canvas')).objectService.listForPage(1).some(x=>x.text==='Edited draft Ω Ж')")
 # Rotation and crop offsets must survive both source-edit paths.
 page.locator('input[type=file][accept*="pdf"]').first.set_input_files(str(Path('regression-fixtures/studio/rotated-cropped.pdf').resolve()))
 page.wait_for_timeout(1800)
 data=page.evaluate("async()=>{let c=ng.getComponent(document.querySelector('app-studio-canvas'));await c.facade.ensureCurrentPageContent();return c.objectService.listForPage(1)}")
 text=next(x for x in data if x.get('text')=='Edit this original sentence')
 page.get_by_role('button',name='Edit PDF Text',exact=True).click()
 page.locator('[data-object-id="'+text['id']+'"]').click()
 page.get_by_role('textbox',name='Edit PDF text',exact=True).fill('Rotated replacement text')
 page.get_by_role('button',name='Finish text edit',exact=True).click()
 page.get_by_role('button',name='Edit PDF Image',exact=True).click()
 image=next(x for x in data if x['type']=='image')
 with page.expect_file_chooser() as chooser:page.locator('[data-object-id="'+image['id']+'"]').click()
 chooser.value.set_files(str(Path('regression-fixtures/studio/replacement.png').resolve()))
 page.wait_for_function("ng.getComponent(document.querySelector('app-studio-canvas')).objectService.listForPage(1).some(x=>x.pdfImage?.replaced)")
 with page.expect_download() as d:page.get_by_role('button',name='Export PDF',exact=True).click()
 d.value.save_as(out/'rotated-edited.pdf')
 page.wait_for_timeout(1000)
 page.wait_for_function("ng.getComponent(document.querySelector('app-studio-canvas')).committedPreview()")
 page.screenshot(path=str(out/'rotated-preview.png'),full_page=True)
 # A duplicate must keep the edits without extra source hit regions.
 page.evaluate("ng.getComponent(document.querySelector('app-studio-canvas')).facade.duplicateCurrentPage()")
 data=page.evaluate("async()=>{let c=ng.getComponent(document.querySelector('app-studio-canvas'));await c.facade.ensureCurrentPageContent();return c.objectService.listForPage(c.facade.currentPage())}")
 assert len([x for x in data if x.get('pdfText',{}).get('originalText')=='Edit this original sentence'])==1
 assert any(x.get('text')=='Rotated replacement text' for x in data)
 sample=Path(os.environ.get('STUDIO_SAMPLE_PDF','/nonexistent'))
 if sample.is_file():
  # Validate the user's actual 15 MB sample as well as synthetic geometry.
  page.locator('input[type=file][accept*="pdf"]').first.set_input_files(str(sample.resolve()))
  page.wait_for_function("name=>ng.getComponent(document.querySelector('app-studio-canvas')).facade.document()?.name===name",arg=sample.name,timeout=60000)
  page.wait_for_timeout(2500)
  data=page.evaluate("async()=>{let c=ng.getComponent(document.querySelector('app-studio-canvas'));await c.facade.ensureCurrentPageContent();return c.objectService.listForPage(1)}")
  (out/'real-sample-objects.json').write_text(json.dumps(data,indent=2))
  text=next(x for x in data if x.get('pdfText') and len(x.get('text',''))>10)
  page.get_by_role('button',name='Edit PDF Text',exact=True).click()
  page.locator('[data-object-id="'+text['id']+'"]').click()
  page.get_by_role('textbox',name='Edit PDF text',exact=True).fill('Studio text editing verified')
  with page.expect_download(timeout=90000) as d:page.get_by_role('button',name='Export PDF',exact=True).click()
  d.value.save_as(out/'real-sample-edited.pdf')
  page.wait_for_timeout(1000)
  page.wait_for_function("ng.getComponent(document.querySelector('app-studio-canvas')).committedPreview()",timeout=90000)
  page.screenshot(path=str(out/'real-sample-preview.png'),full_page=True)
 print('TEXT AND IMAGE UI EXPORT COMPLETE',flush=True)
 browser.close()
